# Use a imagem base do Node.js
FROM node:latest

RUN apt-get update && \
    apt-get install -y python3 python3-pip python3-venv

# Defina o diretório de trabalho
WORKDIR /src

# Copie os arquivos de configuração do Node.js
COPY package*.json ./

# Instale as dependências do Node.js
RUN npm install

# Copie o restante dos arquivos do projeto
COPY . .

# Crie e ative o ambiente virtual para Python
RUN python3 -m venv /usr/src/app/python/venv

# Ative o ambiente virtual e instale as dependências Python
RUN /usr/src/app/python/venv/bin/pip install --upgrade pip && \
    /usr/src/app/python/venv/bin/pip install -r python/requirements.txt

# Exponha a porta que o aplicativo vai usar
EXPOSE 3000

# Comando para iniciar o aplicativo Node.js
CMD ["npm", "run", "start"]
