openapi: 3.0.0
info:
  title: Item and Sala API
  description: API for managing items and salas
  version: 1.0.0
servers:
  - url: https://tcc-senai.onrender.com/api
    description: Production server
  - url: http://localhost:3000/api
    description: Local server
paths:
  /itens:
    get:
      summary: Retrieve all items
      tags:
        - Itens
      responses:
        "200":
          description: List of items
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Item"
  /itens/{externalId}:
    get:
      summary: Get item by ID
      tags:
        - Itens
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
          description: Item ID
      responses:
        "200":
          description: Item data
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Item"
        "404":
          description: Item not found
    patch:
      summary: Update an existing item
      tags:
        - Itens
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
          description: Item ID
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ItemUpdateDTO"
      responses:
        "204":
          description: Item updated successfully
        "400":
          description: Validation error or file upload error
        "404":
          description: Item not found
    delete:
      summary: Delete an item by ID
      tags:
        - Itens
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
          description: Item ID
      responses:
        "204":
          description: Item deleted successfully
        "404":
          description: Item not found
  # /itens/paged:
  #   get:
  #     summary: List paginated itens
  #     tags:
  #       - Itens
  #     responses:
  #       "200":
  #         description: Item data
  #         content:
  #           application/json:
  #             schema:
  #               $ref: "#/components/schemas/Item"
  /salas:
    get:
      summary: Retrieve all salas
      tags:
        - Salas
      responses:
        "200":
          description: List of salas
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Sala"
  /salas/{localizacao}:
    get:
      summary: Get sala by ID
      tags:
        - Salas
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
          description: Sala ID
      responses:
        "200":
          description: Sala data
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Sala"
        "404":
          description: Sala not found
    patch:
      summary: Update an existing sala
      tags:
        - Salas
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
          description: Sala ID
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/SalaUpdateDTO"
      responses:
        "204":
          description: Sala updated successfully
        "400":
          description: Validation error
        "404":
          description: Sala not found
    delete:
      summary: Delete a sala by ID
      tags:
        - Salas
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
          description: Sala ID
      responses:
        "204":
          description: Sala deleted successfully
        "404":
          description: Sala not found
  /salas/paged:
    get:
      summary: List paginated salas
      tags:
        - Salas
      responses:
        "200":
          description: Sala data
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Sala"
  /salas/{localizacao}/itens:
    get:
      summary: Retrieve all items for a specific sala
      tags:
        - Salas
      parameters:
        - in: path
          name: localizacao
          required: true
          schema:
            type: integer
          description: Localização da sala
      responses:
        "200":
          description: List of items for the specified sala
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Item"
        "404":
          description: Sala not found
        "400":
          description: Invalid localizacao parameter
  /auth/login:
    post:
      summary: Realiza o login do usuário
      tags:
        - Auth
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginDTO'
      responses:
        "200":
          description: Login bem-sucedido
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
                    description: Token JWT gerado para autenticação.
                  user:
                    $ref: '#/components/schemas/UserResponseDTO'
        "400":
          description: Requisição inválida (ex. validação falhou)
  /auth/signup:
    post:
      summary: Realiza o cadastro de um novo usuário
      tags:
        - Auth
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SignupDTO'
      responses:
        "201":
          description: Cadastro realizado com sucesso
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserResponseDTO'
        "400":
          description: Requisição inválida (ex. validação falhou)
  /users:
    get:
      summary: Retorna uma lista de usuários paginado
      tags:
        - Users
      responses:
        "201":
          description: lista dos users
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserResponseDTO'
components:
  schemas:
    Item:
      type: object
      properties:
        id:
          type: integer
          example: 1
        nome:
          type: string
        dataDeIncorporacao:
          type: string
          format: date
        status:
          type: string
          enum:
            - DISPONIVEL
            - BAIXA
            - EM_MANUTENCAO
        url:
          type: string
        salaId:
          type: integer
    ItemDTO:
      type: object
      required:
        - nome
        - dataDeIncorporacao
        - status
        - salaId
      properties:
        nome:
          type: string
        dataDeIncorporacao:
          type: string
          format: date
        status:
          type: string
          enum:
            - DISPONIVEL
            - BAIXA
            - EM_MANUTENCAO
        url:
          type: string
        salaId:
          type: integer
    ItemUpdateDTO:
      type: object
      properties:
        nome:
          type: string
        dataDeIncorporacao:
          type: string
          format: date
        status:
          type: string
          enum:
            - DISPONIVEL
            - BAIXA
            - EM_MANUTENCAO
        url:
          type: string
        salaId:
          type: integer
    Sala:
      type: object
      properties:
        id:
          type: integer
          example: 1
        localizacao:
          type: integer
        nome:
          type: string
    SalaDTO:
      type: object
      required:
        - localizacao
        - nome
      properties:
        localizacao:
          type: integer
        nome:
          type: string
    SalaUpdateDTO:
      type: object
      properties:
        nome:
          type: string

    LoginDTO:
      type: object
      properties:
        email:
          type: string
          format: email
          example: usuario@exemplo.com
          description: Email do usuário.
        senha:
          type: string
          example: senha123
          description: Senha do usuário.
      required:
        - email
        - senha

    SignupDTO:
      type: object
      properties:
        nome:
          type: string
          example: João Silva
          description: Nome do usuário.
        email:
          type: string
          format: email
          example: usuario@exemplo.com
          description: Email do usuário.
        senha:
          type: string
          example: senha123
          description: Senha do usuário (mínimo 6 caracteres).
        role:
          type: string
          enum:
            - USER
            - ADMIN
          example: USER
          description: Papel do usuário na aplicação (opcional).
      required:
        - nome
        - email
        - senha
    UserResponseDTO:
      type: object
      properties:
        id:
          type: integer
          example: 1
          description: ID do usuário.
        nome:
          type: string
          example: João Silva
          description: Nome do usuário.
        email:
          type: string
          example: usuario@exemplo.com
          description: Email do usuário.
        role:
          type: string
          example: USER
          description: Papel do usuário na aplicação.

