openapi: 3.0.0
info:
  title: Item and Sala API
  description: API for managing items and salas
  version: 1.0.0
servers:
  - url: https://tcc-senai.onrender.com/api
    description: Production server
  - url: http://localhost:3000/api
    description: Local server
paths:
  /itens:
    get:
      summary: Retrieve all items
      tags:
        - Items
      responses:
        "200":
          description: List of items
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Item"
    post:
      summary: Create a new item
      tags:
        - Items
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ItemDTO"
      responses:
        "201":
          description: Item created successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Item"
        "400":
          description: Validation error or file upload error
  /itens/{id}:
    get:
      summary: Get item by ID
      tags:
        - Items
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
          description: Item ID
      responses:
        "200":
          description: Item data
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Item"
        "404":
          description: Item not found
    patch:
      summary: Update an existing item
      tags:
        - Items
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
          description: Item ID
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ItemUpdateDTO"
      responses:
        "204":
          description: Item updated successfully
        "400":
          description: Validation error or file upload error
        "404":
          description: Item not found
    delete:
      summary: Delete an item by ID
      tags:
        - Items
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
          description: Item ID
      responses:
        "204":
          description: Item deleted successfully
        "404":
          description: Item not found
  /salas:
    get:
      summary: Retrieve all salas
      tags:
        - Salas
      responses:
        "200":
          description: List of salas
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Sala"
    post:
      summary: Create a new sala
      tags:
        - Salas
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/SalaDTO"
      responses:
        "201":
          description: Sala created successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Sala"
        "400":
          description: Validation error
  /salas/{id}:
    get:
      summary: Get sala by ID
      tags:
        - Salas
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
          description: Sala ID
      responses:
        "200":
          description: Sala data
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Sala"
        "404":
          description: Sala not found
    patch:
      summary: Update an existing sala
      tags:
        - Salas
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
          description: Sala ID
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/SalaUpdateDTO"
      responses:
        "204":
          description: Sala updated successfully
        "400":
          description: Validation error
        "404":
          description: Sala not found
    delete:
      summary: Delete a sala by ID
      tags:
        - Salas
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
          description: Sala ID
      responses:
        "204":
          description: Sala deleted successfully
        "404":
          description: Sala not found
components:
  schemas:
    Item:
      type: object
      properties:
        id:
          type: integer
          example: 1
        nome:
          type: string
        dataDeIncorporacao:
          type: string
          format: date
        status:
          type: string
          enum:
            - DISPONIVEL
            - BAIXA
            - EM_MANUTENCAO
        url:
          type: string
        salaId:
          type: integer
    ItemDTO:
      type: object
      required:
        - nome
        - dataDeIncorporacao
        - status
        - salaId
      properties:
        nome:
          type: string
        dataDeIncorporacao:
          type: string
          format: date
        status:
          type: string
          enum:
            - DISPONIVEL
            - BAIXA
            - EM_MANUTENCAO
        url:
          type: string
        salaId:
          type: integer
    ItemUpdateDTO:
      type: object
      properties:
        nome:
          type: string
        dataDeIncorporacao:
          type: string
          format: date
        status:
          type: string
          enum:
            - DISPONIVEL
            - BAIXA
            - EM_MANUTENCAO
        url:
          type: string
        salaId:
          type: integer
    Sala:
      type: object
      properties:
        id:
          type: integer
          example: 1
        localizacao:
          type: integer
        nome:
          type: string
    SalaDTO:
      type: object
      required:
        - localizacao
        - nome
      properties:
        localizacao:
          type: integer
        nome:
          type: string
    SalaUpdateDTO:
      type: object
      properties:
        nome:
          type: string
